/**
 * This class is generated by jOOQ
 */
package com.example.jooq_generated.tables.records;


import com.example.jooq_generated.tables.Contact;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.TableRecordImpl;


/**
 * 联系人
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContactRecord extends TableRecordImpl<ContactRecord> implements Record5<String, String, String, String, String> {

    private static final long serialVersionUID = -2137110764;

    /**
     * Setter for <code>contact.NAME</code>. 姓名
     */
    public void setName(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>contact.NAME</code>. 姓名
     */
    public String getName() {
        return (String) get(0);
    }

    /**
     * Setter for <code>contact.PHONE</code>. 电话
     */
    public void setPhone(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>contact.PHONE</code>. 电话
     */
    public String getPhone() {
        return (String) get(1);
    }

    /**
     * Setter for <code>contact.EMAIL</code>. 邮箱
     */
    public void setEmail(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>contact.EMAIL</code>. 邮箱
     */
    public String getEmail() {
        return (String) get(2);
    }

    /**
     * Setter for <code>contact.GROUPING</code>. 分组 jobName
     */
    public void setGrouping(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>contact.GROUPING</code>. 分组 jobName
     */
    public String getGrouping() {
        return (String) get(3);
    }

    /**
     * Setter for <code>contact.IS_ENABLE</code>. 0 禁用 1 启动
     */
    public void setIsEnable(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>contact.IS_ENABLE</code>. 0 禁用 1 启动
     */
    public String getIsEnable() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<String, String, String, String, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<String, String, String, String, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Contact.CONTACT.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Contact.CONTACT.PHONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Contact.CONTACT.EMAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Contact.CONTACT.GROUPING;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Contact.CONTACT.IS_ENABLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getPhone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getGrouping();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getIsEnable();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContactRecord value1(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContactRecord value2(String value) {
        setPhone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContactRecord value3(String value) {
        setEmail(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContactRecord value4(String value) {
        setGrouping(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContactRecord value5(String value) {
        setIsEnable(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContactRecord values(String value1, String value2, String value3, String value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ContactRecord
     */
    public ContactRecord() {
        super(Contact.CONTACT);
    }

    /**
     * Create a detached, initialised ContactRecord
     */
    public ContactRecord(String name, String phone, String email, String grouping, String isEnable) {
        super(Contact.CONTACT);

        set(0, name);
        set(1, phone);
        set(2, email);
        set(3, grouping);
        set(4, isEnable);
    }
}
