/**
 * This class is generated by jOOQ
 */
package com.example.jooq_generated.tables.records;


import com.example.jooq_generated.tables.JobHistory;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.TableRecordImpl;


/**
 * 任务执行记录
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JobHistoryRecord extends TableRecordImpl<JobHistoryRecord> implements Record3<String, String, Timestamp> {

    private static final long serialVersionUID = 1937145997;

    /**
     * Setter for <code>job_history.JOB_NAME</code>. 任务名
     */
    public void setJobName(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>job_history.JOB_NAME</code>. 任务名
     */
    public String getJobName() {
        return (String) get(0);
    }

    /**
     * Setter for <code>job_history.JOB_LOG</code>. 执行日志
     */
    public void setJobLog(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>job_history.JOB_LOG</code>. 执行日志
     */
    public String getJobLog() {
        return (String) get(1);
    }

    /**
     * Setter for <code>job_history.CREATE_DATE</code>. 创建时间
     */
    public void setCreateDate(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>job_history.CREATE_DATE</code>. 创建时间
     */
    public Timestamp getCreateDate() {
        return (Timestamp) get(2);
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, String, Timestamp> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, String, Timestamp> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return JobHistory.JOB_HISTORY.JOB_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return JobHistory.JOB_HISTORY.JOB_LOG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return JobHistory.JOB_HISTORY.CREATE_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getJobName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getJobLog();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getCreateDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JobHistoryRecord value1(String value) {
        setJobName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JobHistoryRecord value2(String value) {
        setJobLog(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JobHistoryRecord value3(Timestamp value) {
        setCreateDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JobHistoryRecord values(String value1, String value2, Timestamp value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JobHistoryRecord
     */
    public JobHistoryRecord() {
        super(JobHistory.JOB_HISTORY);
    }

    /**
     * Create a detached, initialised JobHistoryRecord
     */
    public JobHistoryRecord(String jobName, String jobLog, Timestamp createDate) {
        super(JobHistory.JOB_HISTORY);

        set(0, jobName);
        set(1, jobLog);
        set(2, createDate);
    }
}
