/**
 * This class is generated by jOOQ
 */
package com.example.jooq_generated.tables;


import com.example.jooq_generated.DefaultSchema;
import com.example.jooq_generated.Keys;
import com.example.jooq_generated.tables.records.JobParamRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * 定时任务参数
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JobParam extends TableImpl<JobParamRecord> {

    private static final long serialVersionUID = -34350601;

    /**
     * The reference instance of <code>job_param</code>
     */
    public static final JobParam JOB_PARAM = new JobParam();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<JobParamRecord> getRecordType() {
        return JobParamRecord.class;
    }

    /**
     * The column <code>job_param.JOB_NAME</code>. 任务名
     */
    public final TableField<JobParamRecord, String> JOB_NAME = createField("JOB_NAME", org.jooq.impl.SQLDataType.VARCHAR.length(100).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "任务名");

    /**
     * The column <code>job_param.PARAM_KEY</code>. 参数名
     */
    public final TableField<JobParamRecord, String> PARAM_KEY = createField("PARAM_KEY", org.jooq.impl.SQLDataType.VARCHAR.length(30).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "参数名");

    /**
     * The column <code>job_param.PARAM_VALUE</code>. 参数值
     */
    public final TableField<JobParamRecord, String> PARAM_VALUE = createField("PARAM_VALUE", org.jooq.impl.SQLDataType.VARCHAR.length(200).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "参数值");

    /**
     * The column <code>job_param.IS_ENABLE</code>. 0 禁用 1 启动
     */
    public final TableField<JobParamRecord, String> IS_ENABLE = createField("IS_ENABLE", org.jooq.impl.SQLDataType.CHAR.length(1).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.CHAR)), this, "0 禁用 1 启动");

    /**
     * Create a <code>job_param</code> table reference
     */
    public JobParam() {
        this("job_param", null);
    }

    /**
     * Create an aliased <code>job_param</code> table reference
     */
    public JobParam(String alias) {
        this(alias, JOB_PARAM);
    }

    private JobParam(String alias, Table<JobParamRecord> aliased) {
        this(alias, aliased, null);
    }

    private JobParam(String alias, Table<JobParamRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "定时任务参数");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<JobParamRecord>> getKeys() {
        return Arrays.<UniqueKey<JobParamRecord>>asList(Keys.KEY_JOB_PARAM_UNIQUE_JOB_NAME_PARAM_KEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JobParam as(String alias) {
        return new JobParam(alias, this);
    }

    /**
     * Rename this table
     */
    public JobParam rename(String name) {
        return new JobParam(name, null);
    }
}
