/**
 * This class is generated by jOOQ
 */
package com.example.dao;


import com.example.dao.tables.Example;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Schema extends SchemaImpl {

    private static final long serialVersionUID = 1889875002;

    /**
     * The reference instance of <code>schema</code>
     */
    public static final Schema SCHEMA = new Schema();

    /**
     * 示例
     */
    public final Example EXAMPLE = com.example.dao.tables.Example.EXAMPLE;

    /**
     * No further instances allowed
     */
    private Schema() {
        super("schema", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Example.EXAMPLE);
    }
}
