/*
 * This file is generated by jOOQ.
*/
package com.example.dao;


import com.example.dao.tables.User;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>schema.user</code>.
     */
    public static final User USER = com.example.dao.tables.User.USER;
}
