/**
 * This class is generated by jOOQ
 */
package com.example.dao;


import com.example.dao.tables.Example;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * 示例
     */
    public static final Example EXAMPLE = com.example.dao.tables.Example.EXAMPLE;
}
