/**
 * This class is generated by jOOQ
 */
package com.example.jooq_generated;


import com.example.jooq_generated.tables.Contact;
import com.example.jooq_generated.tables.Job;
import com.example.jooq_generated.tables.JobParam;
import com.example.jooq_generated.tables.records.ContactRecord;
import com.example.jooq_generated.tables.records.JobParamRecord;
import com.example.jooq_generated.tables.records.JobRecord;

import javax.annotation.Generated;

import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code></code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ContactRecord> KEY_CONTACT_UNIQUE_NAME_GROUPING = UniqueKeys0.KEY_CONTACT_UNIQUE_NAME_GROUPING;
    public static final UniqueKey<JobRecord> KEY_JOB_PRIMARY = UniqueKeys0.KEY_JOB_PRIMARY;
    public static final UniqueKey<JobParamRecord> KEY_JOB_PARAM_UNIQUE_JOB_NAME_PARAM_KEY = UniqueKeys0.KEY_JOB_PARAM_UNIQUE_JOB_NAME_PARAM_KEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<ContactRecord> KEY_CONTACT_UNIQUE_NAME_GROUPING = createUniqueKey(Contact.CONTACT, "KEY_contact_UNIQUE_NAME_GROUPING", Contact.CONTACT.NAME, Contact.CONTACT.GROUPING);
        public static final UniqueKey<JobRecord> KEY_JOB_PRIMARY = createUniqueKey(Job.JOB, "KEY_job_PRIMARY", Job.JOB.JOB_NAME);
        public static final UniqueKey<JobParamRecord> KEY_JOB_PARAM_UNIQUE_JOB_NAME_PARAM_KEY = createUniqueKey(JobParam.JOB_PARAM, "KEY_job_param_UNIQUE_JOB_NAME_PARAM_KEY", JobParam.JOB_PARAM.JOB_NAME, JobParam.JOB_PARAM.PARAM_KEY);
    }
}
