/**
 * This class is generated by jOOQ
 */
package com.example.jooq_generated;


import com.example.jooq_generated.tables.Contact;
import com.example.jooq_generated.tables.Job;
import com.example.jooq_generated.tables.JobHistory;
import com.example.jooq_generated.tables.JobParam;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in 
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * 联系人
     */
    public static final Contact CONTACT = com.example.jooq_generated.tables.Contact.CONTACT;

    /**
     * 定时任务
     */
    public static final Job JOB = com.example.jooq_generated.tables.Job.JOB;

    /**
     * 任务执行记录
     */
    public static final JobHistory JOB_HISTORY = com.example.jooq_generated.tables.JobHistory.JOB_HISTORY;

    /**
     * 定时任务参数
     */
    public static final JobParam JOB_PARAM = com.example.jooq_generated.tables.JobParam.JOB_PARAM;
}
