/*
 * This file is generated by jOOQ.
*/
package com.example.dao.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class User implements Serializable {

    private static final long serialVersionUID = -207297765;

    private final Long   id;
    private final String account;
    private final String password;

    public User(User value) {
        this.id = value.id;
        this.account = value.account;
        this.password = value.password;
    }

    public User(
        Long   id,
        String account,
        String password
    ) {
        this.id = id;
        this.account = account;
        this.password = password;
    }

    public Long getId() {
        return this.id;
    }

    public String getAccount() {
        return this.account;
    }

    public String getPassword() {
        return this.password;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("User (");

        sb.append(id);
        sb.append(", ").append(account);
        sb.append(", ").append(password);

        sb.append(")");
        return sb.toString();
    }
}
